### ISSUE TITLE
Loaders for simulation data and measurement data.

### ISSUE THREAD

**Issue by YooSunYoung** [scipp/essnmx#6]
There is a slight difference between simulation data and measurement data
In the measurement data, event data is provided per detector and simulation data has all event data in one place.
So for the measurement data, there is one more step to combine data sets from all detectors.

We also need to make small mcstas simulation data for testing.

**Comment by YooSunYoung** [comment]
We still don't have real measurement data, so it's blocked for now.

**Comment by SimonHeybrock** [comment]
Consider to just close it, since the simulation case is done and it may be a a long time before we have other files? There is no important info in the thread, I think?

**Comment by YooSunYoung** [comment]
We will close this issue for now, and will open another one for measurement data loader.
